backend:
  name: git-gateway
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - name: "livres"
    label: "Livres"
    folder: "content/livres"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Image de couverture", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "presse"
    label: "Presse"
    folder: "content/presse"
    create: true
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "thumbnail", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - name: "accueil"
        label: "Page d'accueil"
        file: "content/pages/accueil.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Contenu", name: "body", widget: "markdown" }
